### ISSUE TITLE
No module named paho

### ISSUE THREAD

**Issue by PedroVenancio** [DomenicoM92/Nuclear-Energy-Plant-Radiations-#8]
Hi,

It seems that the plugin needs paho.mqtt:

```
Couldn't load plugin 'Nuclear-Energy-Plant-Radiations-' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'paho' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/PedroVenancio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Nuclear-Energy-Plant-Radiations-\__init__.py", line 35, in classFactory
    from .nuclear_energy_plant_radiation_module import energy_plant_radiation_class
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/PedroVenancio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Nuclear-Energy-Plant-Radiations-\nuclear_energy_plant_radiation_module.py", line 6, in 
    from .mqttSubscriber import mqttSubscriber
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/PedroVenancio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Nuclear-Energy-Plant-Radiations-\mqttSubscriber.py", line 1, in 
    import paho.mqtt.client as mqtt
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'paho'
```

Can you please provide info about this requirement and describe how to satisfy it?

**Comment by DomenicoM92** [comment]
Which OS are you using?

**Comment by PedroVenancio** [comment]
@DomenicoM92 Windows 10 and QGIS installed from OSGeo4W 64bits.

**Comment by DomenicoM92** [comment]
Paho-mqtt is module that enable publish/subscribe communication protocol. It simulate the data that comes from sensors. The problems is generate because paho-mqtt is an external module and it can't found by qgis. I fixed it added the library locally. Unfortunately another problems arise. The plugins uses three threads, one of this must update GUI interface (it must update heatmap when data comes). A thread cannot update a GUI in qgis, only Main thread can do it, therefor, for GUI update I've used the follow import: 
from gi.repository import GObject

and the follow instrunction for call the update GUI function:

GObject.idle_add(updteRadiation)

I can't import the module gi.repository, but in linux it works fine while in windows doesn't work!

**Comment by DomenicoM92** [comment]
Hi, I've fixed, now it is cross platform.

**Comment by PedroVenancio** [comment]
Great @DomenicoM92 !
Thank you very much!

**Comment by DomenicoM92** [comment]
Your welcome, the working version is 1.7.
